<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ComposicionRazaSeeder extends Seeder {
    public function run() {
        DB::table('composicion_razas')->insert(collect([
            ['id' => 1, 'nombre' => 'Shortorn', 'siglas' => 'SHO', 'pelaje' => 'Rojo-Blanco', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Noroeste Inglaterra', 'caracteristica_especial' => 'Adaptabilidad', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 2, 'nombre' => 'Hereford', 'siglas' => 'HER', 'pelaje' => 'Colorado Bayo y manchas blancas en la cabeza', 'proposito' => 'Carne', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Suroeste Inglaterra', 'caracteristica_especial' => 'madurez precoz', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 3, 'nombre' => 'Aberdeen Angus', 'siglas' => 'ANG', 'pelaje' => 'Negro o Rojo', 'proposito' => 'Carne', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Escocia', 'caracteristica_especial' => 'longevidad', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 4, 'nombre' => 'Charolais', 'siglas' => 'CHA', 'pelaje' => 'Blanco Crema', 'proposito' => 'Carne', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Charolles -Francia', 'caracteristica_especial' => 'gran musculatura', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 5, 'nombre' => 'Simmental', 'siglas' => 'SIM', 'pelaje' => 'Amarillo castaño a rojo', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Valle Simme - Suiza', 'caracteristica_especial' => 'Docil', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 6, 'nombre' => 'Chianina', 'siglas' => 'CHI', 'pelaje' => 'Blanco solido', 'proposito' => 'Carne', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Valle de chiana - Italia', 'caracteristica_especial' => 'facil manejo', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 7, 'nombre' => 'Romagnola', 'siglas' => 'ROM', 'pelaje' => 'Blanco renegrido', 'proposito' => 'Carne', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Italia', 'caracteristica_especial' => 'Musculoso', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 8, 'nombre' => 'Marchigiana', 'siglas' => 'MAR', 'pelaje' => 'blanco o gris claro', 'proposito' => 'Carne', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Italia', 'caracteristica_especial' => 'Gran tamaño', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 9, 'nombre' => 'Piemontesa', 'siglas' => 'PIE', 'pelaje' => 'Blanco grisaceo o crema', 'proposito' => 'Carne', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Norte de Italia', 'caracteristica_especial' => 'Doble musculo', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 10, 'nombre' => 'Red Poll', 'siglas' => 'RPO', 'pelaje' => 'Rojo', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Inglaterra', 'caracteristica_especial' => 'No tiene cuernos', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 11, 'nombre' => 'Romosinuano', 'siglas' => 'ROMO', 'pelaje' => 'Rojo', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Colombia', 'caracteristica_especial' => 'No tiene cuernos', 'proporcion_raza' => 'Mediano', 'tipo_animal_id' => 1],
            ['id' => 12, 'nombre' => 'Senepol', 'siglas' => 'SEN', 'pelaje' => 'Rojo', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Isla St.Croix', 'caracteristica_especial' => 'No tiene cuernos', 'proporcion_raza' => 'Mediano', 'tipo_animal_id' => 1],
            ['id' => 13, 'nombre' => 'Guzerat', 'siglas' => 'GUZ', 'pelaje' => 'Blanco o gris', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Indicus', 'origen' => 'India', 'caracteristica_especial' => 'Rusticidad', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 14, 'nombre' => 'Nelore', 'siglas' => 'NEL', 'pelaje' => 'Blanco', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Indicus', 'origen' => 'Madras - India', 'caracteristica_especial' => 'Rusticidad', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 15, 'nombre' => 'GYR', 'siglas' => 'GYR', 'pelaje' => 'Marron con manchas blancas', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Indicus', 'origen' => 'Gujarat - India', 'caracteristica_especial' => 'Rusticidad', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 16, 'nombre' => 'Indubrasil', 'siglas' => 'IND', 'pelaje' => 'Blanco o gris', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Indicus', 'origen' => 'Brasil', 'caracteristica_especial' => 'Rusticidad', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 17, 'nombre' => 'Brahman', 'siglas' => 'BRA', 'pelaje' => 'Blanco o Rojo', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Indicus', 'origen' => 'Texas - USA', 'caracteristica_especial' => 'Rusticidad', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 18, 'nombre' => 'Holstein', 'siglas' => 'HOL', 'pelaje' => 'Despigmentacion', 'proposito' => 'Leche', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Holanda', 'caracteristica_especial' => 'Alta produccion', 'proporcion_raza' => 'Grande', 'tipo_animal_id' => 1],
            ['id' => 19, 'nombre' => 'Pardo Suizo', 'siglas' => 'PS', 'pelaje' => 'Color pardo', 'proposito' => 'Leche', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Suiza', 'caracteristica_especial' => 'Caminadora', 'proporcion_raza' => 'Mediana', 'tipo_animal_id' => 1],
            ['id' => 20, 'nombre' => 'Carora', 'siglas' => 'CAR', 'pelaje' => 'Blanco', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Carora - Venezuela', 'caracteristica_especial' => 'Adaptable', 'proporcion_raza' => 'Mediana', 'tipo_animal_id' => 1],
            ['id' => 21, 'nombre' => 'Jersey', 'siglas' => 'JER', 'pelaje' => 'Beige', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Reino Unido', 'caracteristica_especial' => 'Alta eficiencia', 'proporcion_raza' => 'Pequeña', 'tipo_animal_id' => 1],
            ['id' => 22, 'nombre' => 'Guernsey', 'siglas' => 'GUE', 'pelaje' => 'Dorado', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Reino Unido', 'caracteristica_especial' => 'Calidad de leche', 'proporcion_raza' => 'Pequeña', 'tipo_animal_id' => 1],
            ['id' => 23, 'nombre' => 'Ayrshire', 'siglas' => 'AYR', 'pelaje' => 'Rojo y blano', 'proposito' => 'Doble', 'tipo_raza' => 'Bos Taurus', 'origen' => 'Escocia', 'caracteristica_especial' => 'Adaptable a clima frio', 'proporcion_raza' => 'Mediana', 'tipo_animal_id' => 1],
        ])->map(fn($item) => array_merge($item, ['created_at' => now(), 'updated_at' => now()]))->toArray());
    }
}
